module.exports = [
    'Advice on funding',
    'Bootstrapping',
    'Building a team',
    'Content marketing',
    'Conversion rate optimization',
    'Copywriting',
    'No-code',
    'Link building',
    'Mindset coaching',
    'Marketing automation',
    'Idea validation',
    'Growth marketing',
    'Go to market strategy',
    'Email marketing',
    'Design / UX',
    'Data science',
    'Customer success',
    'Product marketing',
    'Product market fit',
    'Product management',
    'Product launches',
    'Product analytics',
    'Pricing strategy',
    'PPC strategies',
    'Productized services',
    'Public relations',
    'User research',
    'Venting frustration',
    'Technology and tools',
    'Social media',
    'SEO',
    'Sales',
    'Remote work'
]